// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keqembvmfcuzggsgzxud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlcWVtYnZtZmN1emdnc2d6eHVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjE2NjYsImV4cCI6MjA2MjYzNzY2Nn0.qZ5zeNue_cMTCiy-4ZxA-42fQxPGQxmr97RLhx90xQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);